admin:
    path:     /admin
    defaults: { _controller: SmartStartBundle:Default:admin }
smart_start_homepage:
    path:     /
    defaults: { _controller: SmartStartBundle:Default:index }

create:
    path:     /create
    defaults: { _controller: SmartStartBundle:Challenge:create }

read:
    path:     /read
    defaults: { _controller: SmartStartBundle:Challenge:read }

update:
    path:     /update/{id}
    defaults: { _controller: SmartStartBundle:Challenge:update }

delete:
    path:     /delete/{id}
    defaults: { _controller: SmartStartBundle:Challenge:delete }
