fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
smart_start:
    resource: "@SmartStartBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
