Avisfreelancer:
    type: entity
    table: avisfreelancer
    indexes:
        idFreelancer:
            columns:
                - idFreelancer
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        description:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        note:
            type: integer
            nullable: false
            options:
                unsigned: false
    manyToOne:
        idfreelancer:
            targetEntity: FosUser
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                idFreelancer:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
