Mission:
    type: entity
    table: mission
    indexes:
        idEntreprise:
            columns:
                - idEntreprise
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        duree:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        hebergement:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        prix:
            type: float
            nullable: false
            precision: 10
            scale: 0
        transport:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        nombrepersonne:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: nombrePersonne
    manyToOne:
        identreprise:
            targetEntity: FosUser
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                idEntreprise:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
