Projet:
    type: entity
    table: projet
    indexes:
        idEntreprise:
            columns:
                - idEntreprise
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nom:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        description:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        domaine:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        budget:
            type: float
            nullable: false
            precision: 10
            scale: 0
        delai:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
    manyToOne:
        identreprise:
            targetEntity: FosUser
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                idEntreprise:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
