Reclamation:
    type: entity
    table: reclamation
    indexes:
        idFreelancer:
            columns:
                - idFreelancer
        idEntreprise:
            columns:
                - idEntreprise
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        titre:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        description:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
    manyToOne:
        identreprise:
            targetEntity: FosUser
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                idEntreprise:
                    referencedColumnName: id
            orphanRemoval: false
        idfreelancer:
            targetEntity: FosUser
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                idFreelancer:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
